### PR TITLE
Support PyCharm EAP 211.*

### PR DESCRIPTION
**Pull request by koxudaxi**
https://github.com/koxudaxi/poetry-pycharm-plugin/issues/179

### CODE REVIEW

**Comment by koxudaxi** [comment]
@sproshev 
I create a PR for EAP 211.
Would you please review this PR?

**Comment by sproshev** [comment]
looks good to me :)

**Comment by koxudaxi** [comment]
@sproshev 
Thank you for your comment!!
Would you have another plan of changes on EAP 211 that is related to Python SDK?

**Comment by sproshev** [comment]
There could be changes related to sdk but I hope they won't affect poetry plugin. I'll ask teammates, personally I don't plan any further changes in 211.

**Comment by koxudaxi** [comment]
@sproshev 
OK, I will release this version soon.
If you get information changes, then could you please notice to me?
Thank you.

**Comment by sproshev** [comment]
Sure, I planned to inform but didn't expect that you'll move poetry plugin to 211 so soon :)

**Pull request merged**
